### ISSUE TITLE
TypeError: Cannot read property 'rows' of undefined dockerized - redis

### ISSUE THREAD

**Issue by Helix-me** [buanet/docker-iobroker#104]
Hi!
I try to start iobroker and redis together in a docker-compose.

Unfortunately the start fails with the following error message:
```bash
iobroker    | Cannot read property 'rows' of undefined
iobroker    | TypeError: Cannot read property 'rows' of undefined
iobroker    |     at /opt/iobroker/node_modules/iobroker.js-controller/main.js:2247:24
iobroker    |     at /opt/iobroker/node_modules/iobroker.objects-redis/index.js:1:111067
iobroker    |     at tryCatcher (/opt/iobroker/node_modules/standard-as-callback/built/utils.js:11:23)
iobroker    |     at /opt/iobroker/node_modules/standard-as-callback/built/index.js:19:49
iobroker    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Is there anything to consider with the environment variables?

### My doker-compose.yml
```yaml
version: '2'

services:
    iobroker:
        restart: always
        image: buanet/iobroker:v4.2.1beta
        container_name: iobroker
        hostname: iobroker
        ports:
        - "8081:8081"
        volumes:
        - ./iobroker/data:/opt/iobroker
        restart: always
        networks:
            - iobroker-network
        environment:
            AVAHI: "true"
            SETUID: 1000
            SETGID: 1000
            TZ: Europe/Berlin
            IOB_OBJECTSDB_HOST: redis
            IOB_OBJECTSDB_PORT: 6379
            IOB_OBJECTSDB_TYPE: "redis"
            IOB_STATESDB_HOST: redis 
            IOB_STATESDB_PORT: 6379
            IOB_STATESDB_TYPE: "redis"
        depends_on:
            - "redis"
    redis:
        image: redis:6.0.3-buster
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./redis/data:/data
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        container_name: redis
        networks:
            - iobroker-network

networks:
    iobroker-network:
        driver: bridge

```
