### ISSUE TITLE
can't get it to run on Raspberry Pi 4 - all time rejected :(

### ISSUE THREAD

**Issue by nicedevil007** [buanet/docker-iobroker#140]
Heya,

I have a raspberry pi 4 with 4 gb ram.

Now I just try to get iobroker running in my docker environment and it is always rejecting.
I run docker in swarm mode to be able to use stacks in portainer.

I also tryed the image buanet/iobroker:arm7hf without success.

Can anyone help?

```
version: '3.7'

volumes:
  iobroker_data:
  
networks:
 hostnet:
   external: true
   name: host

services:
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    hostname: iobroker
    networks:
     hostnet: {}
    ports:
      - 8081:8081
    volumes:
      - iobroker_data:/opt/iobroker
    environment:
      TZ: Europe/Berlin
      LANG: de_DE.UTF-8
      LANGUAGE: de_DE:de
      LC_ALL: de_DE.UTF-8
      PACKAGES: nano
      SETGID: 1000
      SETUID: 1000
```

![image](https://user-images.githubusercontent.com/17103076/96333510-a96cf500-106a-11eb-9997-7bdb2ea4fbec.png)
