### ISSUE TITLE
docker-compose.yml

### ISSUE THREAD

**Issue by PapaSpik3** [buanet/docker-iobroker#47]
Hallo André,

erstmal vielen Dank für deine tolle Arbeit!
Ich habe dein Image unter Debian 10.1 laufen und soweit funktioniert auch fast alles.

Die Einschränkung bezieht sich auf die Environment-Variable zwar kann ich die Pakete angeben aber leider werden diese beim Starten nicht installiert, genauso wie die Sprache / Location und soweiter. Vielleicht könntest du eine Beispiel yml Datei bereitstellen?

Das ist meine:

```
version: "3"

services:
  iobroker:
    container_name: iobroker
    image: buanet/iobroker:latest
    hostname: iobroker
    domainname: fritz.box
    ports:
      #- "1880:1880"  #node-red
      - 1883:1883  #mqtt
      #- "2001:2001"  #homematic
      - 8081:8081  #iobroker admin
      #- "8282:8282"  #flot
      #- "8088:8088"  #terminal
      - 8284:8284  #socketIO
    environment:
      PACKAGES: virtualpowermeter sonoff
      AVAHI: "false"
      LANGUAGE: de_DE:de
      LANG: de_DE.UTF-8
      LC_ALL: de_DE
      TZ: Europe/Berlin
      SETUID: 1000
      SETGID: 1000
      ZWAVE: "false"
    volumes:
      - './data/opt-iobroker/:/opt/iobroker/'
    restart: always
```

Ich hatte auch bereits alles in Anführungszeichen ging leider auch nicht.

Docker version 19.03.4, build 9013bf583a
docker-compose version 1.21.0

Vielen Dank
