### ISSUE TITLE
docker-compose Readme-Beispiel - Korrekturvorschlag

### ISSUE THREAD

**Issue by mephistomuckl** [buanet/docker-iobroker#85]
Bei mir war zum erfolgreichen Ausführen des docker-compose Beispiels aus der Readme eine kleine Korrektur notwendig in der letzten Zeile.

Lediglich "./" hinzugefügt.

```
version: '2'

services:
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    ports:
      - "8081:8081"
    volumes:
      - ./iobrokerdata:/opt/iobroker
```
