### ISSUE TITLE
readme.md / docker-compose.yml incomplete

### ISSUE THREAD

**Issue by ranseyer** [buanet/docker-iobroker#94]
You could add:

```
volumes:
  iobrokerdata:

```

Without this lines the container was not started. (Ubuntu 20.04, Docker CE, Intel CPU)

**Comment by buanet** [comment]
Sorry, don't get it. Please give some more details.
This is the compose file from readme.md:

```
version: '2'

services:
  iobroker:
    restart: always
    image: buanet/iobroker:latest
    container_name: iobroker
    hostname: iobroker
    ports:
      - "8081:8081"
    volumes:
      - iobrokerdata:/opt/iobroker
```
So "volumes" is still included. Thanks.

Regards,
André
